name: Agro Data Ingestion

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install sqlalchemy psycopg2-binary pandas requests

      - name: Run Pipeline
        env:
          
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        run: python src/scripts/main_pipeline.py